# Generated by Django 5.2.7 on 2025-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_to_be_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
