# Generated by Django 5.2.7 on 2025-10-15 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id_attraction', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('counter', models.IntegerField(default=0)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='events.event')),
            ],
        ),
    ]
