# Generated by Django 5.2.7 on 2025-10-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id_attraction', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('counter', models.IntegerField(default=0)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id_qr', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('qr_string', models.CharField(max_length=255, unique=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='events.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.attraction')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.user')),
            ],
        ),
    ]
