# Generated by Django 5.2.7 on 2025-10-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id_attraction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='QR',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
