# Generated by Django 5.2.8 on 2025-11-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
