# Generated by Django 5.2.8 on 2025-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Muzyka'), ('art', 'Sztuka'), ('food', 'Jedzenie'), ('sport', 'Sport'), ('business', 'Business'), ('theatre', 'Teatr'), ('tech', 'Technologia'), ('wellness', 'Wellness'), ('gaming', 'Gaming'), ('film', 'Film'), ('fashion', 'Moda'), ('books', 'Książki'), ('other', 'Inne')], default='other', max_length=50),
        ),
    ]
