# Generated by Django 5.2.8 on 2026-01-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='max_participants',
        ),
    ]
