
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: qentry_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: qentry_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"

#volumes:
#  postgres_data:
