# Generated by Django 5.2.7 on 2025-10-13 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0002_remove_transaction_id_attraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id_qr', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('qr_string', models.CharField(max_length=255, unique=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='events.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='events.attraction')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.user')),
            ],
        ),
    ]
