# Generated by Django 5.2.7 on 2025-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='user_role',
            field=models.CharField(choices=[('guest', 'Gość'), ('staff', 'Personel'), ('token_seller', 'Kasjer')], default='guest', max_length=20),
        ),
    ]
