# Generated by Django 5.2.8 on 2025-12-04 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('tokens', '0002_qr_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='attractions.attraction'),
        ),
    ]
