# Generated by Django 5.2.7 on 2025-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_qr_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='user_role',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
