# Generated by Django 5.2.8 on 2025-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('attraction', 'Attraction'), ('topup', 'TopUp')], default='attraction', max_length=20),
        ),
    ]
