# Generated by Django 5.2.7 on 2025-11-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id_attraction', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('counter', models.IntegerField(default=0)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='events.event')),
            ],
        ),
    ]
